### ISSUE TITLE
Create C++ implementation of Canny's

### ISSUE THREAD

**Issue by marktrovinger** [isaiahfisher/ParallelizingCannyEdgeDetection#1]
Currently the serial implementation of Canny's is written in Python. I personally don't have a problem with that, but I doubt Dr. Khalifa will think the same. For the basic implementation, the following steps will be used.

Steps:
- [ ] Continue to use OpenCV so we don't have to write Gaussian Blur
- [ ] Follow the algorithm as it appears in the Python version
- [ ] Test using well-known images against the Python implementation, to make sure we didn't make any mistakes

**Comment by isaiahfisher** [comment]
@marktrovinger this issue is now closed as a combined effort of my initial development of the Canny implementation in C++ and @omeryurd working to polish and debug my implementation into a working state.
